language: java
jdk:
- oraclejdk8
before_install:
- git clone -b travis `git config --get remote.origin.url` target/travis
branches:
  except:
  - travis
script:
- mvn verify
- mvn deploy --settings target/travis/settings.xml -X
env:
  global:
  - secure: MuEae+s98aQp2YcdI9h5aVZAxZ4B9Wqz9SVYZ4KPEkRgUvYa8OFjbmas+mysisi1+riB+9tFseBHQkq/0D0z+PtIb4xi6MRIiLrBIjuauPVkF5piGuvYJciftfz2Zi5IuGOm4kj69QGpM5JUeVgVZ/MB+rl6/GqIXkKlpZvfFztbshnipnoWXwO64VigVt3KD5wdZ4Jg8AynLukwIgnc0j8BE4m+cGB5E6KBnIozxyJmg1A1/TCvGBJt2HDgqvhbz7zAd+regVIt2lBr4TuIdUDypiVrTpvwr1XiDEoprDN2W3wRnje7pkONSn9Kxs/397E+Qq56226tr0N0PMk1G4tfQEEVmCOt6FUtNhIVXr2PNjayVbOf/kxjW30tp8whAE3e9zLDt6WvO3X5wjkXbXHBzNPIUwwj8Kduqzl9XmGGFDoceKp+ljwHmBGdZI9LGSHuf3tfbpXlj/DdGjQCCuZbhn5shERdVzbUqQ6xqXMQAEmf6axNrQy1fHE8wEm5XzKHICDfJ+d0cSlYE1XYSJbILnq7ry5gHtLHirLWL5o0DNWxFy5c0NH7ldDHLTFxU+nwhYoVumyumPI+bzmygXg3SMv3kYa49OrS+zleeD0PMmGXv35Vq2GeIX5boYocbakHALRyD7RPlbK6HJqra0QU02iIT3ZiaB4Mx667aIw=
  - secure: qjq5IYo43g6hf5blMGkPRA71yTIT4EYYPETeLeGidPuOf0bWqLsYwdpsm63v2GirVaFqb9tF4EbrlF1Elh22wyh1kwhKFlqjLB8HD+ozCNkD5OXVC9PZdfJF4q6dhaVHvc+jROKjiDx/pG9LXCaBK2MJj5EuxBJcfg4tdK2Kkgxw2Z3CQy1iPe6q+omjdI8gSIxFD/5Si270WYXoxnkAzrec8CZ1Ks+YMcJYMAl9ZZtK7owqVHVZc4qHsCn5DveHoATlTlUyTSLc45SCgtf5wlJ+SqfHAnllzW/UHJKmGovd8LhMTGqMjUSToWfQD7uq9853Sx1JrilHFrLIdXQKgtWqZqpMZfilxTxxrUjPMzotRelcosSsOyC3fAbITcCepmZBnLhKcGEPGeLIfnXay0tJbbr/e32+cHXJc3Npd13CIAXvCiv1tJOAOXNZyczUk+M/CjIFHh7bYZdZrCpxFEoYepHMnVlFoO5OhWDfkKVeNYOF38aWfoi8QLwMnKgLl9Sy7HBWpjRMS8quqzCXvkmKp5uwkLVAuz3Mg2pJk2cpVR+2ODIlEh2ZfwKCL8zxSPCxGGfyg2z24WUpz6uwg/VjeN7tHONnsy+O4EC7L8a+StXrhM/zdiR3qQQdkZmq028mECARSKDyQQd8n5xkUTs0QZTlv4ZojH9PRcfkGZk=
